### ISSUE TITLE
Create a User Story

### ISSUE THREAD

**Issue by KashCodes** [Coding-Bootcamp-Survival-Guide/Coding-Bootcamp-Survival-Guide#3]
Let's have everyone give their best 2-3 sentence User Story and we can use them all to create a finalized one. Please add yours to the comments below.

SG took a stab at the user story based on what I think I as hearing from Kash: 
[Bootcamp Survival Guide User Story.pdf](https://github.com/Coding-Bootcamp-Survival-Guide/Coding-Bootcamp-Survival-Guide/files/6174445/Bootcamp.Survival.Guide.User.Story.pdf)

**Comment by gwarzecha** [comment]
GW- As a bootcamp or prospective bootcamp student, I would like an application that allows me to see and comment on blog posts from other bootcamp students and industry professionals. When in need of resources, I am presented with a list of useful documents in an easy-to-navigate area. When looking at potential bootcamps to attend, I am presented with reviews from other bootcamp students and graduates to help inform my decision.
