### ISSUE TITLE
Pick New Package/Library

### ISSUE THREAD

**Issue by KashCodes** [Coding-Bootcamp-Survival-Guide/Coding-Bootcamp-Survival-Guide#9]
- [ ] https://www.npmjs.com/package/captcha (SG had error when installing)
- [ ] https://blog.mailtrap.io/sending-emails-with-nodemailer/
- [ ] https://www.npmjs.com/package/svg-captcha

**Comment by gwarzecha** [comment]
For our front-end CSS framework I propose Tailwind CSS. I've heard quite a bit about it in various podcasts and articles. They also have what appears to be an easily-implementable dark-mode toggle. Totally open to other suggestions, just thought I'd throw it out there.
